// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDjqOiWsIXof43wDqgc_5sk-KNZ9m5uJYc',
//     appId: '1:586849908529:web:19b0843d97f64933786210',
//     messagingSenderId: '586849908529',
//     projectId: 'brezie-d61c0',
//     authDomain: 'brezie-d61c0.firebaseapp.com',
//     storageBucket: 'brezie-d61c0.appspot.com',
//     measurementId: 'G-TF9DPR4X1W',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyByWX_6lq8XDQ05B2ZBGmsnXbVpuqSaO9k',
//     appId: '1:586849908529:android:8216ad0226ce7442786210',
//     messagingSenderId: '586849908529',
//     projectId: 'brezie-d61c0',
//     storageBucket: 'brezie-d61c0.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDKHVjHvZ4DHNIE1Ws2Jv9TiLI7uXFYf6A',
//     appId: '1:586849908529:ios:561ba48d3104936b786210',
//     messagingSenderId: '586849908529',
//     projectId: 'brezie-d61c0',
//     storageBucket: 'brezie-d61c0.appspot.com',
//     iosBundleId: 'com.example.brezie',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDKHVjHvZ4DHNIE1Ws2Jv9TiLI7uXFYf6A',
//     appId: '1:586849908529:ios:561ba48d3104936b786210',
//     messagingSenderId: '586849908529',
//     projectId: 'brezie-d61c0',
//     storageBucket: 'brezie-d61c0.appspot.com',
//     iosBundleId: 'com.example.brezie',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDjqOiWsIXof43wDqgc_5sk-KNZ9m5uJYc',
//     appId: '1:586849908529:web:93dbf94bb3b13c53786210',
//     messagingSenderId: '586849908529',
//     projectId: 'brezie-d61c0',
//     authDomain: 'brezie-d61c0.firebaseapp.com',
//     storageBucket: 'brezie-d61c0.appspot.com',
//     measurementId: 'G-WJ4MSVK08S',
//   );

// }